config/routes.rb
Fae::Engine.routes.draw do

  mount Judge::Engine => '/judge'

  root 'pages#home'

  devise_for :users, class_name: "Fae::User", module: :devise, skip: [:sessions]
  as :user do
    get 'login' => '/devise/sessions#new', as: :new_user_session
    post 'login' => '/devise/sessions#create', as: :user_session
    get 'logout' => '/devise/sessions#destroy', as: :destroy_user_session
  end
  resources :users

  get 'settings' => 'users#settings', as: 'settings'
  get 'help' => 'pages#help', as: 'help'
  get 'activity' => 'pages#activity_log', as: 'activity_log'
  post 'activity/filter' => 'pages#activity_log_filter', as: 'activity_log_filter'

  get 'first_user' => 'setup#first_user'
  post 'first_user' => 'setup#create_first_user'

  # AJAX
  delete 'files/:id/delete_file' => 'files#delete_file', as: :delete_file
  delete 'images/:id/delete_image' => 'images#delete_image', as: :delete_image

  post 'toggle/:object/:id/:attr', to: 'utilities#toggle', as: 'toggle'
  post 'sort/:object', to: 'utilities#sort', as: 'sort'
  post 'language_preference/:language', to: 'utilities#language_preference'
  post 'search/:query', to: 'utilities#global_search'
  post 'search', to: 'utilities#global_search'
  post 'html_embedded_image', to: 'images#create_html_embedded'

  get '/root' => 'options#edit', as: :option
  match '/root' => 'options#update', via: [:put, :patch]

  get 'pages' => '/admin/content_blocks#index', as: 'pages'
  get 'content_blocks/:slug' => '/admin/content_blocks#edit', as: 'edit_content_block'
  match 'content_blocks/:slug/update' => '/admin/content_blocks#update', via: [:put, :patch], as: 'update_content_block'

  # catch all 404
  match "*path" => 'pages#error404', via: [:get, :post]

end

app/models/concerns/fae/assets_validatable.rb
module Fae::AssetsValidatable
  extend ActiveSupport::Concern

  included do
    validate :asset_exists
  end

  def asset_exists
    errors.add(:asset, "#{self.class.to_s.gsub('Fae::','')} can't be empty") if required && asset.blank?
  end

end

app/models/concerns/fae/authorization_concern.rb
module Fae
  module AuthorizationConcern
    extend ActiveSupport::Concern
    module ClassMethods

      def access_map
        {}
      end

    end
  end
end

app/models/concerns/fae/base_model_concern.rb
module Fae
  module BaseModelConcern
    extend ActiveSupport::Concern
    require 'csv'

    attr_accessor :filter

    included do
      include Fae::Trackable if Fae.track_changes
      include Fae::Sortable
    end

    def fae_display_field
      # override this method in your model
    end

    def fae_nested_parent
      # override this method in your model
    end

    def fae_tracker_parent
      # override this method in your model
    end

    def fae_nested_foreign_key
      return if fae_nested_parent.blank?
      "#{fae_nested_parent}_id"
    end

    module ClassMethods
      def for_fae_index
        order(order_method)
      end

      def order_method
        klass = name.constantize
        if klass.column_names.include? 'position'
          return :position
        elsif klass.column_names.include? 'name'
          return :name
        elsif klass.column_names.include? 'title'
          return :title
        else
          raise "No order_method found, please define for_fae_index as a #{name} class method to set a custom scope."
        end
      end

      def filter(params)
        # override this method in your model
        for_fae_index
      end

      def fae_search(query)
        all.to_a.keep_if { |i| i.fae_display_field.present? && i.fae_display_field.to_s.downcase.include?(query.downcase) }
      end

      def to_csv
        CSV.generate do |csv|
          csv << column_names
          all.each do |item|
            csv << item.attributes.values_at(*column_names)
          end
        end
      end

      def fae_translate(*attributes)
        attributes.each do |attribute|
          define_method attribute.to_s do
            self.send "#{attribute}_#{I18n.locale}"
          end

          define_singleton_method "find_by_#{attribute}" do |val|
            self.send("find_by_#{attribute}_#{I18n.locale}", val)
          end
        end
      end

      def has_fae_image(image_name_symbol)
        has_one image_name_symbol, -> { where(attached_as: image_name_symbol.to_s) },
          as: :imageable,
          class_name: '::Fae::Image',
          dependent: :destroy
        accepts_nested_attributes_for image_name_symbol, allow_destroy: true
      end

      def has_fae_file(file_name_symbol)
        has_one file_name_symbol, -> { where(attached_as: file_name_symbol.to_s) },
          as: :fileable,
          class_name: '::Fae::File',
          dependent: :destroy
        accepts_nested_attributes_for file_name_symbol, allow_destroy: true
      end

    end

    private

    def fae_bust_navigation_caches
      Fae::Role.all.each do |role|
        Rails.cache.delete("fae_navigation_#{role.id}")
      end
    end

  end
end

app/models/concerns/fae/change_concern.rb
module Fae::ChangeConcern; end

app/models/concerns/fae/file_concern.rb
module Fae::FileConcern; end

app/models/concerns/fae/image_concern.rb
module Fae::ImageConcern; end

app/models/concerns/fae/navigation_concern.rb
module Fae
  module NavigationConcern
    extend ActiveSupport::Concern

    def structure
      []
    end

  end
end

app/models/concerns/fae/option_concern.rb
module Fae::OptionConcern; end

app/models/concerns/fae/page_validatable.rb
module Fae::PageValidatable
  extend ActiveSupport::Concern

  def validators(page_class)
    self.class.validators_on(:content).keep_if { |amv| is_valid_validator?(amv, page_class) }
  end

  def validation_json(page_class)
    validators(page_class).map { |v| Judge::Validator.new(self, :content, v).to_hash }.to_json
  end

  def is_required?(page_class)
    required = false
    validators(page_class).each do |amv|
      required = true if amv.class.name['PresenceValidator']
    end
    required
  end

  private

  def is_valid_validator?(amv, page_class)
    amv.options[:if].blank? || amv.options[:if] == "is_#{page_class.name.underscore}_#{attached_as}?".to_sym
  end

end

app/models/concerns/fae/paper_trailer.rb
module Fae::PaperTrailer
  extend ActiveSupport::Concern

  included do
    has_paper_trail ignore: [:updated_at]
  end

end

app/models/concerns/fae/role_concern.rb
module Fae::RoleConcern; end

app/models/concerns/fae/sortable.rb
module Fae
  module Sortable
    extend ActiveSupport::Concern

    module ClassMethods

      def fae_sort(params)
        return all unless params.present? && params[:sort_by].present?

        attr_parts = params[:sort_by].split('.')

        if attr_parts.length == 1
          order_by_model_attr(attr_parts.first, sort_direction(params[:sort_direction]))
        else
          order_by_association_attr(attr_parts.first.to_sym, attr_parts.second, sort_direction(params[:sort_direction]))
        end
      end

      private

      def order_by_model_attr(sort_by, direction)
        return all unless attribute_exists(self, sort_by)
        unscope(:order).order("#{table_name}.#{sort_by} #{direction}")
      end

      def order_by_association_attr(association, sort_by, direction)
        assoc_index = reflect_on_all_associations.map(&:name).index(association)
        return all unless assoc_index
        order_klass = reflect_on_all_associations[assoc_index].klass

        return all unless attribute_exists(order_klass, sort_by)

        includes(association).unscope(:order).order("#{order_klass.table_name}.#{sort_by} #{direction}")
      end

      def sort_direction(direction_from_params)
        return 'asc' if direction_from_params.blank?

        direction = direction_from_params.downcase
        # verify the direction from parms are legit to protect against injection
        return %w(asc desc).include?(direction) ? direction : 'asc'
      end

      def attribute_exists(klass, attribute)
        klass.column_names.include? attribute
      end

    end

  end
end

app/models/concerns/fae/static_page_concern.rb
module Fae::StaticPageConcern; end

app/models/concerns/fae/text_area_concern.rb
module Fae::TextAreaConcern; end

app/models/concerns/fae/text_field_concern.rb
module Fae::TextFieldConcern; end

app/models/concerns/fae/trackable.rb
module Fae
  module Trackable
    extend ActiveSupport::Concern

    included do
      after_create :add_create_change, if: :track_changes?
      before_update :add_update_change, if: :track_changes?
      before_destroy :add_delete_change, if: :track_changes?

      has_many :tracked_changes, -> { order(id: :desc) },
        as: :changeable,
        class_name: 'Fae::Change'
    end

    def fae_tracker_blacklist
      []
    end

    def track_changes?
      Fae.track_changes && fae_tracker_blacklist != 'all'
    end

    private

    def add_create_change
      return if has_parent?
      attrs = {
        changeable_id: id,
        changeable_type: self_or_super_class_name,
        user_id: Fae::Change.current_user,
        change_type: 'created'
      }
      attrs.merge!(tracker_parent_attrs(attrs[:change_type])) if fae_tracker_parent
      Fae::Change.create(attrs)
    end

    def add_update_change
      if has_parent?
        update_parent
      else
        return if legit_updated_attributes.blank?
        attrs = {
          changeable_id: id,
          changeable_type: self_or_super_class_name,
          user_id: Fae::Change.current_user,
          change_type: 'updated',
          updated_attributes: legit_updated_attributes
        }
        attrs.merge!(tracker_parent_attrs(attrs[:change_type])) if fae_tracker_parent
        Fae::Change.create(attrs)
        clean_history
      end
    end

    def add_delete_change
      return if has_parent?
      attrs = {
        changeable_id: id,
        changeable_type: self_or_super_class_name,
        user_id: Fae::Change.current_user,
        change_type: 'deleted'
      }
      attrs.merge!(tracker_parent_attrs(attrs[:change_type])) if fae_tracker_parent
      Fae::Change.create(attrs)
      clean_history
    end

    def self_or_super_class_name
      self.class.superclass.name == 'Fae::StaticPage' ? 'Fae::StaticPage' : self.class.name
    end

    def legit_updated_attributes
      legit_attributes = changed - ignored_attributes
      if fae_tracker_blacklist.kind_of?(Array) && fae_tracker_blacklist.present?
        legit_attributes -= fae_tracker_blacklist.map(&:to_s)
      end
      legit_attributes
    end

    def ignored_attributes
      ['id', 'updated_at', 'created_at']
    end

    def clean_history
      tracked_changes.offset(Fae.tracker_history_length).destroy_all
    end

    def has_parent?
      %w(Fae::Image Fae::File Fae::TextField Fae::TextArea).include? self.class.name
    end

    def asset_name
      attached_as || self.class.name.gsub('Fae::','').underscore
    end

    def update_parent
      parent = self.try(:imageable) || self.try(:fileable) || self.try(:contentable)
      if parent.present?
        latest_change = parent.try(:tracked_changes).try(:first)
        if latest_change.present? && latest_change.change_type == 'updated' && latest_change.updated_at > 2.seconds.ago
          updated_updated_attributes = latest_change.updated_attributes << asset_name
          latest_change.update_attribute(:updated_attributes, updated_updated_attributes)
        else
          Fae::Change.create({
            changeable_id: parent.id,
            changeable_type: parent.class.name,
            user_id: Fae::Change.current_user,
            change_type: 'updated',
            updated_attributes: [asset_name]
          })
        end
      end
    end

    def tracker_parent_attrs(change_type)
      {
        changeable_id: fae_tracker_parent.id,
        changeable_type: fae_tracker_parent.class.name,
        change_type: "#{self.class.name.titleize} #{fae_display_field} #{change_type}"
      }
    end

  end
end

app/models/concerns/fae/user_concern.rb
module Fae
  module UserConcern
    extend ActiveSupport::Concern
    module ClassMethods
      def available_languages
        [:en]
      end
    end
  end
end

app/models/fae/authorization.rb
module Fae
  class Authorization
    include Fae::AuthorizationConcern

    # `self.access_map` is defined in Fae::AuthorizationConcern on the parent app

  end
end

app/models/fae/change.rb
module Fae
  class Change < ActiveRecord::Base
    include Fae::Sortable
    include Fae::ChangeConcern

    belongs_to :user
    belongs_to :changeable, polymorphic: true

    serialize :updated_attributes

    class << self
      # writing current_user to thread for thread safety
      def current_user=(user)
        Thread.current[:current_user] = user
      end

      def current_user
        Thread.current[:current_user]
      end

      def unique_changeable_types
        pluck(:changeable_type).uniq.sort.map{ |changeable_type| [changeable_type.gsub('Fae::',''), changeable_type] }
      end

      def filter(params)
        # build conditions if specific params are present
        conditions = {}
        conditions[:user_id] = params['user'] if params['user'].present?
        conditions[:changeable_type] = params['model'] if params['model'].present?
        conditions[:change_type] = params['type'] if params['type'].present?

        date_scope = []
        if params['start_date'].present? || params['end_date'].present?
          start_date = params['start_date'].present? ? CGI.unescape(params['start_date']).to_date : nil
          end_date   = params['end_date'].present? ? CGI.unescape(params['end_date']).to_date : nil
          date_scope = ['fae_changes.updated_at >= ?', start_date] if start_date.present?
          date_scope = ['fae_changes.updated_at <= ?', end_date] if end_date.present?
          date_scope = ['fae_changes.updated_at >= ? AND fae_changes.updated_at <= ?', start_date, end_date] if start_date.present? && end_date.present?
        else
          date_scope = case params['date']
            when 'Last Hour' then   ['fae_changes.updated_at >= ?', 60.minutes.ago]
            when 'Last Day' then    ['fae_changes.updated_at >= ?', 1.day.ago]
            when 'Last Week' then   ['fae_changes.updated_at >= ?', 1.week.ago]
            when 'Last Month' then  ['fae_changes.updated_at >= ?', 1.month.ago]
            else
              []
          end
        end

        # use good 'ol MySQL to search if search param is present
        search = []
        if params['search'].present?
          search = ["fae_users.first_name LIKE ? OR fae_users.last_name LIKE ? OR fae_changes.updated_attributes LIKE ? OR fae_changes.changeable_type LIKE ? OR fae_changes.change_type LIKE ?", "%#{params['search']}%", "%#{params['search']}%", "%#{params['search']}%", "%#{params['search']}%", "%#{params['search']}%"]
        end

        # apply conditions and search from above to our scope
        order(id: :desc)
          .includes(:user).references(:user)
          .where(date_scope).where(conditions).where(search)
      end

    end
  end
end

app/models/fae/file.rb
require 'file_size_validator'

module Fae
  class File < ActiveRecord::Base

    include Fae::BaseModelConcern
    include Fae::FileConcern
    include Fae::AssetsValidatable

    mount_uploader :asset, Fae::FileUploader

    validates :asset,
      file_size: {
        maximum: Fae.max_file_upload_size.megabytes.to_i
      }

    belongs_to :fileable, polymorphic: true, touch: true, optional: true

    def readonly?
      false
    end

  end
end

app/views/fae/shared/_errors.slim
- unless flash.present?
  .flash-message.alert.hide = t('fae.save_error')

== render 'flash_messages'

app/views/fae/shared/_form_header.html.slim
ruby:
  require_locals ['header'], local_assigns
  save_button_text    ||= t('fae.form.save')
  cancel_button_text  ||= t('fae.form.cancel')
  cloneable           ||= false
  clone_button_text   ||= t('fae.form.clone')
  subnav              ||= []
  header_as_string      = header.is_a?(String) ? header : header.class.name.split('::').last
  header_as_string      = header_as_string.singularize
  title               ||= "#{params[:action]} #{header_as_string}".titleize
  breadcrumb            = !local_assigns[:breadcrumbs].eql?(false)
  languages           ||= false
  show_flash_messages   = !local_assigns[:show_flash_messages].eql?(false)

header.content-header.js-content-header
  - if breadcrumb
    == render 'breadcrumb', title: title
  - else
    = form_header header

  .content-header-buttons
    - if languages
      - selected = current_user.language || ''

      .content-header-select
        = select_tag 'fae-languages', options_for_select(Fae.languages.map(&:reverse), selected), id: 'js-language', class: 'small_pulldown', prompt: 'All Languages'

    a.button#js-header-cancel href=@index_path = cancel_button_text
    - if cloneable.present? && params[:id].present?
      a.button data-method="post" href="#{@index_path}?from_existing=#{params[:id]}" = clone_button_text
    input name="commit" type="submit" value=save_button_text

  - if subnav.present?
    ul.content-header-subnav#js-content-header-subnav
      - subnav.each do |link, id_selector|
        - subnav_item = link.is_a?(Array) ? link : [link, link.parameterize(separator: '_')]
        li: a href="##{subnav_item[1]}" = subnav_item[0]

- if show_flash_messages
  == render 'fae/shared/errors'

app/views/fae/shared/_index_header.html.slim
ruby:
  nested      ||= false
  title       ||= @klass_humanized.pluralize.titleize
  new_button    = !local_assigns[:new_button].eql?(false)
  new_path    ||= "new_#{fae_path}_#{@klass_singular}_path"
  button_text ||= t('fae.common.add', title: title.singularize)
  export_text ||= t('fae.common.csv_export')
  csv         ||= false
  breadcrumb    = !local_assigns[:breadcrumbs].eql?(false)

header.content-header.js-content-header
  - if breadcrumb
    == render 'breadcrumb'
  - else
    h1 = title

  .content-header-buttons
    - if csv && @items.present?
      a.button href="#{@index_path}.csv" = export_text

    - if new_button
      - if nested
        a.add-button.js-add-link.js-index-add-link remote='true' href=self.send(new_path) = button_text
      - else
        a.add-button href=@new_path = button_text

== render 'flash_messages'

app/views/fae/shared/_nested_table.html.slim
ruby:
  index ||= false

  if index
    require_locals(['assoc'], local_assigns)
  else
    require_locals(['assoc', 'parent_item'], local_assigns)
  end

  # optional locals
  assoc_name          ||= assoc.to_s                      # 'restaurant_bars'
  title               ||= assoc_name.titleize             # 'Restaurant Bars'
  add_button_text     ||= t('fae.common.add', title: title.singularize)
  hide_add_button     ||= false
  ordered             ||= false
  has_thumb           ||= false
  edit_column         ||= false
  cols                ||= []
  helper_text         ||= ''

  # lesser known optional locals, dervived from options by default
  assoc_name_singular ||= assoc_name.singularize          # 'restaurant_bar'
  new_path            ||= "new_#{fae_path}_#{assoc_name_singular}_path"
  edit_path           ||= "edit_#{fae_path}_#{assoc_name_singular}_path"

  begin
    if index
      new_path = self.send(new_path)
    else
      new_path = self.send(new_path, item_id: parent_item.id, item_class: parent_item.class.to_s)
    end
  rescue
    new_path += new_path['?'] ? '&' : '?'
    new_path += "item_id=#{parent_item.id}&=item_class=#{parent_item.class.to_s}"
  end

  options_for_table = { index: index, assoc: assoc, assoc_name: assoc_name, title: title, add_button_text: add_button_text, hide_add_button: hide_add_button, ordered: ordered, has_thumb: has_thumb, edit_column: edit_column, cols: cols, assoc_name_singular: assoc_name_singular, new_path: new_path, edit_path: edit_path }
  options_for_table[:parent_item] = parent_item unless index

section.addedit-form.js-addedit-form class="#{'content' if index}"
  - if index
    == render 'fae/shared/shared_nested_table', options_for_table

  - else
    - unless hide_add_button
      a.js-add-link.table-add-link.button.-small href=new_path = add_button_text
    h2 = title
    - if helper_text.present?
      h6.table-helper-text = helper_text
    == render 'fae/application/flash_messages'
    == render 'fae/shared/shared_nested_table', options_for_table

app/views/fae/shared/_recent_changes.html.slim
- unless params[:action] == 'new'
  .content#recent_changes
    h2 = t('fae.changes.recent')
    section.addedit-form.js-addedit-form
      table
        thead
          tr
            th = t('fae.changes.user')
            th = t('fae.changes.type')
            th = t('fae.changes.attrs')
            th.-action-wide t('fea.changes.modified')
        tbody
          - if @item.try(:tracked_changes).present?
            - @item.tracked_changes.each do |change|
              tr
                td = change.user.full_name if change.user.present?
                td = change.change_type
                td = change.updated_attributes.join(', ') if change.updated_attributes.present?
                td = fae_datetime_format(change.updated_at)
          - else
            tr
              td colspan="4" = t('fae.changes.no_changes')

app/views/fae/shared/_shared_nested_table.html.slim
ruby:
  colspan = cols.length + 1
  colspan += 1 if ordered
  colspan += 1 if has_thumb
  table_class = ordered ? 'js-sort-row' : nil

  options_for_td = { cols: cols, edit_path: edit_path, edit_column: edit_column }

table class=table_class
  thead
    tr
      - if ordered
        th.th-sortable-handle
      - if has_thumb
        th.-thumb
      - cols.each do |col|
        = th_columns(col)
      - if edit_column
        th.-action data-sorter="false"
      th.-action
  tbody
    - records = index ? @items : parent_item.send(assoc)
    - if records.present?
      - records.each do |item|
        tr id=tr_id(item)
          - if ordered
            td.sortable-handle: i.icon-sort
          - if has_thumb
            td = image_tag(item.asset.thumb.url)
          - cols.each do |col|
            - options_for_td[:col] = col
            - options_for_td[:item] = item
            = td_columns(options_for_td)
          - if edit_column
            td
              a.js-edit-link.js-tooltip.table-action title=t('fae.common.edit') href=self.send(edit_path, item)
                i.icon-edit
          td = fae_delete_button item, "/#{fae_path}/#{assoc_name}/#{item.id.to_s}", class: 'js-tooltip table-action js-delete-link', remote: true

    - elsif !hide_add_button
      tr
        - td_link = link_to 'add some', new_path, class: 'js-add-link'

        td colspan=colspan.to_s No #{title} yet, #{td_link}.
    - else
      tr
        td colspan=colspan.to_s No #{title} yet.

.js-addedit-form-wrapper